---
- name: Check if caddy is installed
  tags: caddy
  stat:
    path: /usr/bin/caddy
  register: caddy_config_stat

- name: Install caddy if it is not installed yet
  tags: caddy
  when: not caddy_config_stat.stat.exists
  block:
    - name: Install xcaddy
      tags: caddy
      become: false
      shell: |
        /usr/local/go/bin/go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

    - name: Build Caddy with plugins
      tags: caddy
      become: false
      shell: |
        /home/{{ ansible_ssh_user }}/go/bin/xcaddy build --with github.com/caddyserver/forwardproxy=github.com/klzgrad/forwardproxy@naive --output /home/{{ ansible_ssh_user }}/caddy
      environment:
        PATH: "/usr/local/go/bin:{{ ansible_env.PATH }}"

    - name: Update capabilities of Caddy binary
      tags: caddy
      shell: |
        sudo setcap cap_net_bind_service=+ep /home/{{ ansible_ssh_user }}/caddy

    - name: Move Caddy to /usr/bin
      tags: caddy
      ansible.builtin.copy:
        src: /home/{{ ansible_ssh_user }}/caddy
        dest: /usr/bin/caddy
        remote_src: yes
        owner: root
        group: root
        mode: '0755'

- name: Create caddy config folder
  tags: caddy
  file:
    path: /etc/caddy
    state: directory
    mode: 0777

- name: Create Caddyfile configuration
  tags: caddy
  template:
    src: "templates/Caddyfile.j2"
    dest: "/etc/caddy/Caddyfile"

- name: Install NP server service
  tags: caddy
  include_tasks:
    file: roles/utils/service/tasks/install-services.yaml
    apply: { tags: [ "caddy" ] }
  vars:
    services:
      - name: caddy
        description: Caddy server
        exec: "/usr/bin/caddy run --environ --config /etc/caddy/Caddyfile"
        after_target: network.target
